# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: news.proto

require 'google/protobuf'


descriptor_data = "\n\nnews.proto\x12\x04news\"]\n\x08NewsItem\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\x14\n\x0c\x62\x61nner_image\x18\x04 \x01(\t\x12\x0e\n\x06topics\x18\x05 \x03(\t\",\n\x0cNewsResponse\x12\x1c\n\x04news\x18\x01 \x03(\x0b\x32\x0e.news.NewsItem\"0\n\x0bNewsRequest\x12\x10\n\x08\x66unction\x18\x01 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x02 \x01(\t\"<\n\x0cTopicRequest\x12\x1d\n\x02nr\x18\x01 \x01(\x0b\x32\x11.news.NewsRequest\x12\r\n\x05topic\x18\x02 \x01(\t2}\n\x0bNewsService\x12\x32\n\x07GetNews\x12\x11.news.NewsRequest\x1a\x12.news.NewsResponse\"\x00\x12:\n\x0eGetNewsByTopic\x12\x12.news.TopicRequest\x1a\x12.news.NewsResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module News
  NewsItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("news.NewsItem").msgclass
  NewsResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("news.NewsResponse").msgclass
  NewsRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("news.NewsRequest").msgclass
  TopicRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("news.TopicRequest").msgclass
end
